### ISSUE TITLE
HTML in PDF output

### ISSUE THREAD

**Issue by ross-spencer** [nationalarchives/DiAGRAM#37]
Hi all, just looking at the output today, I see some rogue HTML in the presentation output from the tool. 

![image](https://user-images.githubusercontent.com/1880412/141094510-f7663dad-b43e-4d17-ba17-f33be62677ab.png)

Attached is the full slide-deck. 

Running Chrome, on Windows 11.

[DiAGRAM-2021-11-09.zip](https://github.com/nationalarchives/DiAGRAM/files/7511815/DiAGRAM-2021-11-09.zip)

**Comment by DavidUnderdown** [comment]
Thanks Ross

The PDFs need to be looked at as part of the accessibility work that's currently happening anyway. That will be quite a major rewrite overall, but I'd imagine we'd be able to pick this up as part of that.

**Comment by jwalton3141** [comment]
I believe this issue is now resolved. See the screenshot below from a PDF I generated from diagram.nationalarchives.gov.uk


![image](https://user-images.githubusercontent.com/32269169/196164510-e8713e5c-2a6b-49e6-a168-5cc11bfe32bb.png)
