### ISSUE TITLE
Reference models still show placeholder values

### ISSUE THREAD

**Issue by DavidUnderdown** [nationalarchives/DiAGRAM#56]
looking at https://diagram.nationalarchives.gov.uk/visualise.html I've realised that the two reference models are still showing (the same) placeholder values. Need to make this match the current outputs in https://nationalarchives.shinyapps.io/DiAGRAM/ before we go live with the new version. @jamieRowen

**Comment by DavidUnderdown** [comment]
Original info on the models is in two Google docs:

- [Commercial Backup](https://docs.google.com/document/d/1rllUojYyZlDH4GgbMTQGn9xHiP7WPftXhxHlM9N8kdw/edit)
- [Established National Archive](https://docs.google.com/document/d/1OyNQmL4k59AgeIcihXGi9EbU5Y_r_O5mdOxzBxM_uaY/edit)

**Comment by jwalton3141** [comment]
Hi @DavidUnderdown,

I should be able to pick this issue up (@jamieRowen no longer works at Jumping Rivers). It looks like the changes needed to be made are to this file: https://github.com/nationalarchives/DiAGRAM/blob/live/app/frontend/scripts/example-models.js.

**Comment by DavidUnderdown** [comment]
Thanks Jack: I just noticed this morning that Jamie's Slack account was deactivated. I think Colin reviewed the code in the past too.

**Comment by jwalton3141** [comment]
Closed by #58
