### ISSUE TITLE
Improve navigation by adding links to body text

### ISSUE THREAD

**Issue by DavidUnderdown** [nationalarchives/DiAGRAM#63]
Since we can now link direct to individual pages in DiAGRAM could you add links on [View results](https://diagram.nationalarchives.gov.uk/visualise.html) so that:

- _'Learn about Diagram'_ links to https://diagram.nationalarchives.gov.uk/definitions.html and 
- _'Download a report'_ links to https://diagram.nationalarchives.gov.uk/report.html?

And on Learn about DiAGRAM in turn so that:

- _on the Advanced Customisation page_ links to https://diagram.nationalarchives.gov.uk/advanced.html

Presumably it would be best to do these as relative links so that they always go to the page relevant to the current environment without having to edit in any way?

**Comment by timbrock** [comment]
Should the links open in new tabs?

**Comment by DavidUnderdown** [comment]
I don't think it's necessary to force a new tab for these, unlike the links from the questions flow I don't think you'd lose any state by following the link to get more information and then just use the back button to return to View results or Learn about DiAGRAM.

**Comment by timbrock** [comment]
I've added these on the dev branch
