### ISSUE TITLE
Update version shown on home page and remove prototype label

### ISSUE THREAD

**Issue by DavidUnderdown** [nationalarchives/DiAGRAM#64]
Once we are ready to launch then the version number on the home page should be updated to 1.0.0 and the label "(Prototype)" removed

**Comment by timbrock** [comment]
I've made a draft PR for this that can be removed from draft when ever it's decided it's appropriate.

**Comment by jwalton3141** [comment]
Closed by https://github.com/nationalarchives/DiAGRAM/pull/75
