### ISSUE TITLE
PDF creation failed when an advanced model was selected

### ISSUE THREAD

**Issue by DavidUnderdown** [nationalarchives/DiAGRAM#67]
During a demo I was trying to create a PDF, when the advanced model I'd created was selected PDF creation failed and an error message was returned (no more details included). Deselecting the advanced model and creating with only a simple model and related scenario then I was able to successfully generate a PDF. Both operations were undertaken around 2pm GMT on 3 November 2022. Is there any more info in the logs?

**Comment by DavidUnderdown** [comment]
Tried PDF generation again and was also getting a failure when any scenario was selected (even ordinary ones not created via advanced). I'd created a single model and two scenarios, the second based on the first. Models/scenarios were created at random, not based on a real life situation, so I've attached the JSON file (extension changed to txt as GitHub doesn't support uploading .json)
[models-2023-02-08.txt](https://github.com/nationalarchives/DiAGRAM/files/10688068/models-2023-02-08.txt)

**Comment by jwalton3141** [comment]
I've tracked down the issue with scenarios to [this line](https://github.com/nationalarchives/DiAGRAM/blob/live/api/src/inst/assets/templates/pdf_section.Rmd#L94):
```R
diagramLambda::join_questions_responses(question_data, x) %>%
    diagramLambda::diff_table()
```

within the final code chunk of [`pdf_section.Rmd`](https://github.com/nationalarchives/DiAGRAM/blob/live/api/src/inst/assets/templates/pdf_section.Rmd).

One can recreate the issue, using the json file from above, as:

```R
parsed_json = jsonlite::read_json("models-2023-02-08.txt")
adv_flag = advanced_flags(parsed_json)
data = extract_responses(parsed_json[!adv_flag])

question_data = diagramLambda::get_questions_tibble()
policies = diagramLambda::find_scenario_diffs(data)

x = policies[[1]]
diagramLambda::join_questions_responses(question_data, x) %>%
  diagramLambda::diff_table()
```

The actual error which is raised is: `Error in eval_tidy(xs[[j]], mask) : object '.z' not found`. Which I believe goes down to the function `diagramLambda:::diff_table_part()`, and specifically to the line: `"Base Model Response" = as.character(.z)`. Found [here](https://github.com/nationalarchives/DiAGRAM/blob/live/api/src/R/pdf.R#L264).

I need to understand this issue a bit further before I will be placed to raise a fix.

**Comment by jwalton3141** [comment]
RE. The PDF generation for advanced models not working, that might be why there is a line in the code which simply excludes them from the report generation. See, https://github.com/nationalarchives/DiAGRAM/blob/live/api/src/R/api_report.R#L11 which says:

```R
write_temp_pdf(extract_responses(parsed_json[!adv_flag]))
```

The `[!adv_flag]` will drop advanced models from the PDF output. 

That bit of code goes back in the git history quite a while, so I wonder whether this feature never worked properly? or whether the feature of doing PDF reports for advanced models was simply never finished?

**Comment by DavidUnderdown** [comment]
OK, it now works for a simple model with simple scenarios, or an advanced model/scenario (I created an advanced model based on the existing simple model).

If you try and select a simple model (with or without scenarios) and an advanced model together then it still errors.

I don't know how complex that would be to fix entirely. I guess an option for a quick workaround would be to just display (an accessible) message to the user to ask them to select either advanced models or simple models, but not both at the same time.
